import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { CSSProperties, ReactNode } from "react";
import "./globals.css";
import { AppProviders } from "@/src/providers/app-providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const earlyDisplayScript = `
(() => {
  const bootstrap = window.__BOOKLOG_BOOTSTRAP__;
  const theme = bootstrap && typeof bootstrap === "object" && "theme" in bootstrap ? bootstrap.theme : "system";
  const fontScale = bootstrap && typeof bootstrap === "object" && "fontScale" in bootstrap ? Number(bootstrap.fontScale) : 1;
  const safeTheme = theme === "dark" || theme === "light" || theme === "system" ? theme : "system";
  const safeFontScale = Number.isFinite(fontScale) ? fontScale : 1;
  const resolvedTheme = safeTheme === "system"
    ? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light")
    : safeTheme;
  const html = document.documentElement;
  html.dataset.theme = safeTheme;
  html.classList.toggle("dark", resolvedTheme === "dark");
  html.style.setProperty("--app-font-scale", String(safeFontScale));
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-theme="system"
      style={{ "--app-font-scale": 1 } as CSSProperties}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: earlyDisplayScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
